

PRINT '     _  _                                       '
PRINT '    | || |  _            _                      '
PRINT '    | || |_| |_ ___  ___| |_ _   _ _ __ ___     '
PRINT '    |__   _| __/ _ \/ __| __| | | |  __/ _ \    '
PRINT '       |_| | ||  __/ (__| |_| |_| | | |  __/    '
PRINT '            \__\___|\___|\__|\__,_|_|  \___|    '
PRINT '                                                '
PRINT '        empower your software solutions         '
PRINT '                                                '

PRINT '******************* referencedata scripts *******************'

-- Start transaction for all referencedata scripts
BEGIN TRANSACTION;
BEGIN TRY

    DECLARE @DBEXISTS bit;
    SET @DBEXISTS = 0;

    DECLARE @DBNAME NVARCHAR(128);
    SET @DBNAME = DB_NAME();

    DECLARE @DBID INT;
    SET @DBID = DB_ID();

    IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = @DBNAME)
    BEGIN
        PRINT 'The database ' +  @DBNAME + ' does not yet exist. All referencedata deployment scripts will be skipped.'
        SET @DBEXISTS = 0
    END
    ELSE
    BEGIN
        PRINT 'The database ' +  @DBNAME + ' already exists. referencedata deployment scripts will be executed.'
        SET @DBEXISTS = 1
    END

    -- Only run scripts of type 'pre' if the database exists, otherwise skip.
    IF @DBEXISTS=1 AND 'referencedata'='referencedata'
    BEGIN    
        -- Run the new migration script
        PRINT '------------------ RUN --------------------------'
        PRINT 'Script Id:      ReferenceDataScripts\1_JokeCategories.sql'
        PRINT 'Script Name:    1_JokeCategories.sql'
        PRINT 'Order Criteria: 1'
        PRINT 'Script Type:    referencedata'
        PRINT 'Script Path:    C:\Repos\Demos\DevFun\src\DevFun.Api\DevFun.DB\Scripts\ReferenceDataScripts\1_JokeCategories.sql'
        PRINT 'Script Hash:    K63LGBJvr9KA+84tAiNC0A=='
        
        PRINT ' > Start referencedata-script run....'
        exec('--MERGE generated by ''sp_generate_merge'' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

MERGE INTO [dbo].[Category] AS Target
USING (VALUES
	 (0,''General'')
	,(1,''.NET'')
	,(2,''Java'')
) AS Source ([Id],[Name])
ON (Target.[Id] = Source.[Id])
WHEN MATCHED AND (
	NULLIF(Source.[Name], Target.[Name]) IS NOT NULL OR NULLIF(Target.[Name], Source.[Name]) IS NOT NULL) THEN
 UPDATE SET
  [Name] = Source.[Name]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Name])
 VALUES(Source.[Id],Source.[Name])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT ''ERROR OCCURRED IN MERGE FOR [dbo].[Category]. Rows affected: '' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT ''[dbo].[Category] rows affected by MERGE: '' + CAST(@mergeCount AS VARCHAR(100));
 END

SET NOCOUNT OFF')
        PRINT ' > Finished referencedata-script run....'
        
        PRINT '----------------- END RUN ------------------------'
        PRINT '|'
    END
END TRY
BEGIN CATCH
    DECLARE @ErrorMessage NVARCHAR(4000);
    DECLARE @ErrorSeverity INT;
    DECLARE @ErrorState INT;

    SELECT @ErrorMessage = ERROR_MESSAGE(),
           @ErrorSeverity = ERROR_SEVERITY(),
           @ErrorState = ERROR_STATE();

	-- Rollback all transactions if any of the referencedata scripts failed.
    IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION;

    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH;

-- Commit transaction if all referencedata scripts have been successfully run.
IF @@TRANCOUNT > 0  
    COMMIT TRANSACTION;  
GO